name: CI

on:
  [push, workflow_dispatch, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - uses: actions/checkout@v1
      name: Checkout

    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
      repository: Gwion/GwionSite
      path: GwionSite

    - name: GwionSite tools
      run: bash GwionSite/install.sh

    - name: Dependencies
      run: bash scripts/update.sh

    - name: MdBook
      uses: peaceiris/actions-mdbook@v1
      with:
         mdbook-version: 'latest'

    - name: GIT things
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: Build book
      run: PATH=$PWD:$PATH make build

    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        email: fennecdjay@gmail.com
        jekyll: no
        build_dir: book
